{{- $job := .Values.backend -}}
{{- $jobName := printf "%s-%s" .Release.Name $job.name }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $job.role }}
  annotations: 
    released: {{ .Release.Time }} 
spec:
  schedule: 0 8 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}
            image: {{ $job.image }}:{{ $job.imageTag }}
            command: ["/application/app"]
            args: ["-source=oxr"]
            env:
            {{- range .Values.backend.env }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $jobName }}-env
                  key: {{ . }}
            {{- end }}
          restartPolicy: OnFailure 
